p8015_hw2_cmh2275
================
cmh2275
2026-10-03

# Problem 1

## import data

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
options(tibble.print_min = 5)

transit_df = read_csv (file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
                       col_types = cols(Route8 ="c", Route9 = "c", Route10 = "c", Route11 = "c"), 
                       na=c("NA",".","")) |>
        janitor::clean_names() |>
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) |> 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

## Paragraph re: data

This dataset includes information about the NYC transit station’s
entrances and exits across locations and routes. In additon to
informaiton about the division, line, station names, station locations,
and routes, it provides information about entrance types, entry, exit,
vending, staffing and staff hours, ada compliance, if there is free
crossover, cross streets, and entrance locations, with a total of 32
variables. The dataset was reduced to include 19 variables: line,
station name, station latitude, station longitude, routes 1-11, vending,
entrance type, entry, and ada compliance.The entry variable was
converted from a character yes/no variable to a logical variable. There
are 19 columns and 1868 rows

## questions

``` r
transit_df |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 465 × 2
    ##   station_name line    
    ##   <chr>        <chr>   
    ## 1 25th St      4 Avenue
    ## 2 36th St      4 Avenue
    ## 3 45th St      4 Avenue
    ## 4 53rd St      4 Avenue
    ## 5 59th St      4 Avenue
    ## # ℹ 460 more rows

\*There are 465 distinct stations.

``` r
transit_df |> 
  filter(ada == TRUE) |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 84 × 2
    ##   station_name             line           
    ##   <chr>                    <chr>          
    ## 1 Atlantic Av-Barclays Ctr 4 Avenue       
    ## 2 DeKalb Av                4 Avenue       
    ## 3 Pacific St               4 Avenue       
    ## 4 Grand Central            42nd St Shuttle
    ## 5 34th St                  6 Avenue       
    ## # ℹ 79 more rows

- 85 Stations are ADA compliant.

``` r
transit_df|> 
  filter(vending == "NO") |> 
  pull(entry) |> 
  mean()
```

    ## [1] 0.3770492

- The proportion of stations entrances/exits without vending that allow
  entrance is 0.377.

``` r
transit_df |> 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") |> 
  filter(route == "A") |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 60 × 2
    ##   station_name                  line           
    ##   <chr>                         <chr>          
    ## 1 Times Square                  42nd St Shuttle
    ## 2 125th St                      8 Avenue       
    ## 3 145th St                      8 Avenue       
    ## 4 14th St                       8 Avenue       
    ## 5 168th St - Washington Heights 8 Avenue       
    ## # ℹ 55 more rows

``` r
transit_df |> 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") |> 
  filter(route == "A", ada == TRUE) |> 
  select(station_name, line) |> 
  distinct()
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

- Sixty distinct stations serve the A train.
- Seventeen of the sixty stations that serve the A train are ADA
  compliant.

# Problem 2

## read in data

``` r
library(tidyverse)
library(readxl)

mrtrash_df = (read_excel("./data/202610 Trash Wheel Collection Data.xlsx", sheet = 1, range = "A2:N742", col_names = TRUE ))|>
  janitor::clean_names()|>
  mutate(vessel = "mr", sports_balls = as.integer(sports_balls), year = as.double(year))|>
  relocate(vessel)
```

## read additional data

``` r
proftrash_df = (read_excel("./data/202610 Trash Wheel Collection Data.xlsx", sheet = 2, range = "A2:M139", col_names = TRUE, na = c("", ".", "NA")))|>
  janitor::clean_names()|>
  mutate(vessel = "prof", plastic_bottles = as.double(plastic_bottles)) |>
  relocate(vessel)
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `plastic_bottles = as.double(plastic_bottles)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

``` r
gwynnda_df = (read_excel("./data/202610 Trash Wheel Collection Data.xlsx", sheet = 4, range = "A2:L394", col_names = TRUE, na = c("", ".", "NA"))) |>
  janitor::clean_names()|>
  mutate(vessel = "gwyn")|>
  relocate(vessel)
```

## join datasets

``` r
fulltrash_df = bind_rows(mrtrash_df, proftrash_df, gwynnda_df)
```

## Dataset information

This data set includes 1269 observations. It contains the following
variables: vessel, dumpster, month, year, date, weight_tons,
volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, plastic_bags, wrappers, sports_balls, homes_powered.
These variables describe the trash collected by each trash vessel across
the years.

The total weight of trash collected by Professor Trash Wheel was 294.96
tons.

The total number of cigarette buts collected by Gwynnda in June of 2022
was 18120.

# Problem 3

## import, clean & tidy baseline data

``` r
library(tidyverse)
mcibase_df = read_csv("./data/MCI_baseline.csv", skip = 1, na=c("."))|>
  janitor::clean_names()|>
  rename (baseline_age = current_age)|>
  mutate (
    sex = factor(sex, levels = c(1,0), labels = c("male", "female")),
    apoe4 = factor(apoe4, levels = c(1,0), labels = c("carrier", "noncarrier"))
          )|>
 filter(age_at_onset>baseline_age |is.na(age_at_onset))
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

## Dataset Information

This dataset was imported and variable names were updated. Sex and Apoe4
variables were changed to factors and finally the dataset was filtered
to remove any participants who had MCI diagnosis at baseline. Thus, the
final dataset only includes those who met inlcusion criteria for the
study. It includes four main variables: age at baseline, sex of
participant, years of education, apoe4 status (carrier/noncarrier), and
MCI age onset, with the following variable names: id, baseline_age, sex,
education, apoe4, age_at_onset and has 479 observations.

There were 479 participants recruited, and of them, 93 were diagnosed
with MCI.

The average age at baseline was 65.03 years.

The proportion of women in the study who are APOE4 carrriers is 0.3.

## add biomarker data

``` r
mciamy_df = read_csv("./data/mci_amyloid.csv", skip = 1, na=c(".", "NA", "Na"))|>
  janitor::clean_names() |>
  rename (id = study_id, amyratio_base = baseline, amyratio_time_2 = time_2, amyratio_time_4 = time_4, amyratio_time_6 = time_6, amyratio_time_8 = time_8)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The data was imported, specifying missing values to maintain numeric
variables, and names were cleaned. The study id variable name was
changed from study_id to id to be consistent across study datasets, and
other variable names were changed to better reflect content. The data
includes 487 observations and, in additon to study id, 5 variables that
report the amyloid beta 42/40 ratio across 5 timepoints for the
following variables: id, amyratio_base, amyratio_time_2,
amyratio_time_4, amyratio_time_6, amyratio_time_8.

The amyloid dataset has 487observations while the baseline dataset only
has 479 observations, indicating there are participants that only appear
in one dataset (the amyloid dataset).

## join datasets

``` r
mcifull_df = left_join(mcibase_df, mciamy_df, by = "id")

write_csv (mcifull_df, "hw2_mci_joined.csv")
```

The combined dataset contains only participants who met inclusion
criteria for the study; participants who had MCI at baseline were
excluded. It includes baseline demographics of age at baseline, sex,
years of education, apoe4 carrier status and measures of amyloid beta
42/40 ratios across five timepoints for the following variables id,
baseline_age, sex, education, apoe4, age_at_onset, amyratio_base,
amyratio_time_2, amyratio_time_4, amyratio_time_6, amyratio_time_8, and
has a total of 479 participants (observations).
